manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: d357re
      url-base: https://github.com/d357re
  projects:
    - name: zmk
      remote: d357re
      revision: main
      import: app/west.yml
  self:
    path: config
